### ISSUE TITLE
Any chance of a different name? 

### ISSUE THREAD

**Issue by RedBearAK** [spinda/fantasque-sans-ligatures#1]
@spinda 

Thanks so much for making this fork of Fantasque Sans Mono with the ligatures removed. I followed the link from your post on issue 122 in the original repo. 

I have a suggestion that might make this fork even better. If the font name (internally, and the name of the files) could be changed to make it possible to install this version of the font alongside the original fonts (with ligatures), and somehow be able to tell which is which. Right now it has the same name and installs over the top of the original font. If it were possible to have a different name by adding "noLig" or something, that would be visible in font pickers/installers, I think some would find that very useful. 

Unfortunately in its current state, when I save these files I have to make a folder that explicitly notes these are the "no ligatures" version of the fonts, otherwise I will easily get them confused with the originals archived in my cloud drive when installing them on new machines. I work with a lot of different Linux distributions so I actually end up installing this font quite frequently. 

It's fine if you don't want to go to the trouble of this additional step, this is just a suggestion. I appreciate that you made this fork and put it up.

**Comment by spinda** [comment]
Easily done! I added a `NameSuffix` variant which appends a `noLig` suffix to the family names. Check them out in `v1.8.1`.

**Comment by RedBearAK** [comment]
@spinda 

Hey, thanks for responding to this. I guess it really never hurts to ask. Already downloaded some. 

Just wondering though, did you intend for the archive names to show "NameSuffix" instead of "noLig" to match the internal change to the name? Seems kind of generic. 

```
FantasqueSansMono-LargeLineHeight-NameSuffix.zip
FantasqueSansMono-LargeLineHeight-NoLoopK-NameSuffix.zip
FantasqueSansMono-NameSuffix.zip
FantasqueSansMono-NoLoopK-NameSuffix.zip
```

I kind of expected the archive names to look more like this: 

```
FantasqueSansMono-LargeLineHeight-noLig.zip
FantasqueSansMono-LargeLineHeight-NoLoopK-noLig.zip
FantasqueSansMono-noLig.zip
FantasqueSansMono-NoLoopK-noLig.zip
```

As far as the name internally, that's exactly what I was looking for. But I'm wondering if it's at all complicated to add the string to all the individual font filenames. Again, to reflect what the name is internally. 

```
FantasqueSansMono-noLig-Bold.otf
FantasqueSansMono-noLig-BoldItalic.otf
FantasqueSansMono-noLig-Italic.otf
FantasqueSansMono-noLig-Regular.otf
```

I don't really know how fonts are installed (and how and where the files are stored when they are installed), but it seems like it might be problematic if the name of the font files themselves are still the same as the originals. Even if that is not a problem technically, it still requires separating the files in different folders that declare what they are, rather than being able to just have a copy of my preferred variants of the original and no-ligature version of the font sitting in the same folder (to grab and install quickly). 

What do you think?
